version: "3.0"
services:
  ldapi:
    build: ./Dockerfile
    image: ldapi:latest
    ports:
      - "8001:8001"
    volumes:
      - "./.env:./.env"
      - "./cache:./cache"
    env_file:
      - ./.env
    #command: ["python","main.py"]
