[tool.poetry]
name = "LickingDogAPI"
version = "0.0.1"
description = "舔狗API"
authors = ["llxlr <i@xhlr.top>"]
license = "MIT"

[tool.poetry.dependencies]
aiofiles = "^0.6.0"
aiohttp = "^3.7.4.post0"
baidu-aip = "^2.2.18.0"
beautifulsoup4 = "^4.9.3"
bilibili_api = "^4.0.1"
cffi = "^1.14.4"
cssutils = "^1.0.2"
email-validator = "^1.1.2"
eliot = "^1.13.0"
eliot-tree = "^21.0.0"
fake-useragent = "^0.1.11"
fastapi = "^0.63.0"
faust = "^1.10.4"
gunicorn = "^20.0.4"
Jinja2 = "^3.0.0"
lxml = "^4.6.2"
MyQR = "^2.3.1"
# numpy = "^1.20.0"
orjson = "^3.5.1"
# opencv-python = "^4.4.0.46"
python = "^3.8"
# pandas = "^1.1.4"
Pillow = "^8.1.0"
pixivpy = "^3.5.10"
# playwright = "^0.171.1"
pydantic = "^1.8.1"
# pysnooper = "^0.4.2"
python-dotenv = "^0.15.0"
python-multipart = "^0.0.5"
# PyMySQL = "^0.10.1"
requests = "^2.25.1"
ruia = "^0.8.4"
selenium = "^3.141.0"
slowapi = "^0.1.4"
sqlalchemy = "^1.3.23"
twint = "^2.1.20"
starlette = "^0.13.6"
uvicorn = "^0.13.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
